---
kind: Service
apiVersion: v1
metadata:
  name: reader
spec:
  selector:
    app: reader
  type: NodePort
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader
spec:
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - image: redisreader:latest
        name: reader
        imagePullPolicy: Never #to receive image from local repo
        env:
          - name: REDIS_HOSTNAME
            value: redis
          - name: REDIS_PORT
            value: "6379"
        ports:
        - containerPort: 80